### ISSUE TITLE
Создание прототипов

### ISSUE THREAD

**Issue by YaroslavRostanets** [YaroslavRostanets/FreePark#1]
Создать прототипы всех экранов приложения

**Comment by kifirko** [comment]
процес пошел, но проблема в том что мне не нравится результат.
непонятно почему, то ли потому что оно все чб и ненатуральное, то ли от того что я делаю говно...
![new mockup 1](https://user-images.githubusercontent.com/29466976/27397671-ca6df6a4-56bf-11e7-8ddc-862dc080aaf8.png)

**Comment by YaroslavRostanets** [comment]
Ну блин. Надо точно несколько вариантов.

**Comment by YaroslavRostanets** [comment]
Может не следует зацикливаться на стандартном шаблоне приложений. Типа меню слева выезжает и т.д. 
Вот глянь эту штуку 
https://habrastorage.org/files/7c2/5c5/727/7c25c572765548889543c8df4e81115e.gif
И вообще статью. 
https://habrahabr.ru/post/294282/

**Comment by YaroslavRostanets** [comment]
https://habrahabr.ru/company/appodeal/blog/260095/ и вот

**Comment by kifirko** [comment]
Твои то ссылки ахуенные но оно все в анимации и чисто графическое выглядит все пиздато, но во первых мы так рисовать не умеем а во вторых нам придется идти дальше чем просто анимация
Вот что вышло, пока скучновато но с другими окинками, шрифтами и анимацей будет интересно как у того типа 
![Uploading Знімок екрана 2017-06-26 о 21.10.30.png…]()
