### ISSUE TITLE
Создание preloader/loader

### ISSUE THREAD

**Issue by YaroslavRostanets** [YaroslavRostanets/FreePark#12]
Нужно сделать прикол для загрузки. Фишка в том что когда осуществляется запрос к серверу, то данные приходят не мгновенно, и следующий экран в приложении показывать нельзя, пока нет данных. Но кнопку пользователь уже нажал. Нужно сделать анимацию загрузки, сто бы юзер понимал что прога не зависла, а что-то там происходит. 

- [http://materializecss.com/preloader.html](url)

- [ ] [https://preloaders.net/](url)

**Comment by kifirko** [comment]
надо посмотреть как оно в проге будет 
https://drive.google.com/open?id=0B97CC3_vp9fyRngzZnFjMmZ5dGM
так сложно что то подобрать

**Comment by YaroslavRostanets** [comment]
Я думаю что когда будет что-то загружаться, то на экран вешать полупрозрачный белый слой и лоадер этот по центру экрана.

**Comment by YaroslavRostanets** [comment]
Берем стандартный Андроида пока что
