### ISSUE TITLE
Создание логотипа

### ISSUE THREAD

**Issue by YaroslavRostanets** [YaroslavRostanets/FreePark#14]
Тут в архиве папки со стандартными логотипами. Наши должны точно-так же называться, Разрешение и формат должны быть точно такие же как эти. В идеале если ты мне предоставишь такую же папку с такой же структурой только с нашими логотипами. Я просто закину в приложение.

[res.zip](https://github.com/YaroslavRostanets/FreePark/files/1327816/res.zip)

**Comment by kifirko** [comment]
ознакомился, утвердим лого, сделаю так как в архиве

**Comment by YaroslavRostanets** [comment]
Готово
