### ISSUE TITLE
Логотип и название приложения

### ISSUE THREAD

**Issue by kifirko** [YaroslavRostanets/FreePark#2]
### Придумать название и лого приложения

**Comment by kifirko** [comment]
Реально сложная задача, если с Лобстером все пришлос само собой то тут хз.
Название должно 

1. Говорить о том что данный софт направлен на бесплатные парковки (так как есть аналоги с платными парковками и оплаты таких парковок)
2. Указывать на регион для которого создано приложение 

Есть идеи, которые "Да" но как то "не то":
- [ ] FreePark
*👎 нет и намека на регион 

- [ ] HelPark
*👎 не все поймут что Хел - это хельсинки, плюс если будем расти на соседние города то название будет протироечить сути 

- [ ] Parker
*👍👎 не говорит ни о чем за то оригинально.
*👍 в маркете нет аналогов
*👎 наталкивает на мысль о ручках а не о парковках

**Comment by YaroslavRostanets** [comment]
FreePlace
Вообще название не горит и логотип. Сначала прототипы.

**Comment by kifirko** [comment]
не катит, название вообще не дает понят что речь о автопарковках.
к тому же если и дать понять человеку что речь о парковах то название говорит о свободных местах парковки а не о бесплатных парковках

**Comment by YaroslavRostanets** [comment]
Тогда ФриПарк. Но вообще надо подумать. Пусть будет так. Если появится варик лучше то переназовем.
