### ISSUE TITLE
Разобратся в футкиционале этого блокнота...

### ISSUE THREAD

**Issue by kifirko** [YaroslavRostanets/FreePark#5]
ибо как по мне тупо блокнот

**Comment by YaroslavRostanets** [comment]
Тут просто список задач. Их можно открывать\закрывать. Помечать баги и т.д. 
По ходу проставлять время нельзя. Но хз надо ли оно нам. 
Так же файлы прикреплять можно.

**Comment by kifirko** [comment]
это понятно, но вот например ты закрыл таск. 
а я не могу закрывать таски

**Comment by kifirko** [comment]
аа нашел))))))
